# Generated by Django 2.0.7 on 2019-07-03 13:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TSBserv', '0002_auto_20190702_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStormEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('distance', models.FloatField(default=0)),
                ('latitudeDirection', models.CharField(max_length=1)),
                ('lontitudeDirection', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='dateJoined',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stormEvent',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='TSBserv.UserStormEvent'),
            preserve_default=False,
        ),
    ]
